name = "mttt"
description = "markentier.tech theme"
homepage = "https://github.com/markentier/markentier.tech"
license = "None"
min_version = "0.10"
demo = "https://markentier.tech/"

[author]
name = "Christoph Grabo"
homepage = "https://markentier.tech/"

[extra]
# â€¢â—âœ¿âœ½âˆ·â‰£â‰¡âŠ›â–¢â—â—†ğŸœ‚á¨â•â—Šâ–²â™£â„³â“‚â“œâ‘â‚â€–
# 5: ğ‘‡¥â¸­â™ğ’Šğ’‘ğ„šğŸ€”ğŸ€ğŸ‚¥ğŸ‚µğŸƒ…ğŸƒ• ğŸ¯ğŸ°ğŸ±ğŸ²ğŸ³ğŸ´ğŸŸ‰ğŸŸŠâ›¤â›¥â›¦â›§
# ğ‘‡¥ https://www.compart.com/en/unicode/U+111E5

# Alchemy: https://www.compart.com/en/unicode/search?q=alchemic#characters
# ğŸœ‚ğŸœ„ğŸœğŸœƒğŸœğŸœğŸœ›
# Misc Symbols: https://www.compart.com/en/unicode/block/U+2600
title_sep = "ğŸ³"
